language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install --upgrade pip flake8 pylint pylint pytest pytest-cov codecov
  - pip install -r requirements/development
# command to run tests
script:
  - flake8 apartment_browser
  - pylint apartment_browser
  - pytest
after_success:
  - codecov
