name: Continuous Deployment

# this workflow is only triggered on versions tags (created with bumpversion) after successful CI.
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    tags:
      - 'v*.*.*'
    types: 
      - completed

env:
  PYTHON_VERSION: 3.8

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --dev
    
      - name: Build python package and wheel
        run: python setup.py sdist bdist_wheel
      
      - name: Publish the distribuable to PyPI
        run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
